esphome:
  name: a-30-minimal

esp32:
  board: denky32
wifi:
  ssid: !secret wifi_ssid_ci
  password: !secret wifi_password_ci
  fast_connect: true
  ap:
    ssid: $devicename
    password: !secret ap_password
captive_portal:
web_server:
  port: 80
logger:
  baud_rate: 0
  level: debug
api:
  encryption:
    key: !secret api_key
ota:
  password: !secret ota_password

status_led:
  pin: 2

switch:
  - platform: gpio
    pin: 33
    name: "1"

  - platform: gpio
    pin: 25
    name: "3"

  - platform: gpio
    pin: 5
    name: "5"

  - platform: gpio
    pin: 23
    name: "7"

  - platform: gpio
    pin: 26
    name: "9"

  - platform: gpio
    pin: 22
    name: "11"

  - platform: gpio
    pin: 13
    name: "13"

  - platform: gpio
    pin: 19
    name: "15"

  - platform: gpio
    pin: 27
    name: "2"

  - platform: gpio
    pin: 4
    name: "4"

  - platform: gpio
    pin: 21
    name: "6"

  - platform: gpio
    pin: 25
    name: "8"

  - platform: gpio
    pin: 18
    name: "10"

  - platform: gpio
    pin: 12
    name: "12"

  - platform: gpio
    pin: 14
    name: "14"

  - platform: gpio
    pin: 16
    name: "16"

